version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - WaldoJeffers
  assignees:
  - WaldoJeffers
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: handlebars
    versions:
    - 4.7.6
    - 4.7.7
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: jest
    versions:
    - 26.6.3
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
  - dependency-name: yargs-parser
    versions:
    - 13.1.2
  - dependency-name: acorn
    versions:
    - 5.7.4
  - dependency-name: eslint
    versions:
    - 6.8.0
